"""add reflections table

Revision ID: 0666a5df972d
Revises: 4f978ca6fd62
Create Date: 2026-07-13 16:54:21.064095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0666a5df972d'
down_revision: Union[str, Sequence[str], None] = '4f978ca6fd62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reflections', 'importance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reflections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('reflections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reflections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reflections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reflections', 'importance',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
