"""add memory access tracking

Revision ID: 4f978ca6fd62
Revises: 7ac453175429
Create Date: 2026-07-11 10:21:21.906173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f978ca6fd62'
down_revision: Union[str, Sequence[str], None] = '7ac453175429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('access_count', sa.Integer(), nullable=True))
    op.add_column('memories', sa.Column('last_accessed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'last_accessed')
    op.drop_column('memories', 'access_count')
    # ### end Alembic commands ###
