"""create reflections table

Revision ID: 7ac453175429
Revises: 4c7dc2ddec10
Create Date: 2026-07-10 09:32:29.104523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac453175429'
down_revision: Union[str, Sequence[str], None] = '4c7dc2ddec10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reflections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('reflection', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reflections_id'), 'reflections', ['id'], unique=False)
    op.create_index(op.f('ix_reflections_session_id'), 'reflections', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reflections_session_id'), table_name='reflections')
    op.drop_index(op.f('ix_reflections_id'), table_name='reflections')
    op.drop_table('reflections')
    # ### end Alembic commands ###
